# This is a basic workflow that is manually triggered
name: timersignal

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on schedule
  schedule:
    - cron:  '0/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_schedule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook
      with:
        url: "https://smee.io/bifhbaXwHKBhgBI"
        json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}" }'
