name: timersignal

on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.3
      with:
        url: "https://smee.io/bifhbaXwHKBhgBI"
        json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}" }'
