name: daily_hook

on:
  schedule:
    - cron:  '0 18 * * *'

jobs:
  send_hook:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v2.0.3
      env:
        webhook_url: "https://smee.io/bifhbaXwHKBhgBI"
        webhook_secret: 0c8f7960804f08cdc8a278bdd8fa22cdb7946e9e
